server:
    port: 8080
    servlet:
        context-path: /mypc
        session:
            timeout: 300s

spring:
    application:
        name: MyPC
    profiles:
        active: secret
    security:
        user:
            name: ${mypc.username}
            password: ${mypc.password}

logging.level.root: INFO