server:
    port: 8080
    servlet:
        context-path: /mypc
        session:
            timeout: 300s

spring:
    application:
        name: MyPC
    profiles:
        active: secret
    security:
        user:
            name: ${USERNAME}
            password: ${PASSWORD}

logging.level.root: INFO