server:
  port: 8080
  servlet:
    context-path: /explorer

spring:
  application.name: '@project.artifactId@'
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html