server:
  port: 8080
  servlet:
    context-path: /explorer
    session:
      timeout: 60s

spring:
  application:
    name: MyPC
  profiles:
    active: secret
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}

logging.level.root: INFO