# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    - name: Compile with Maven
      run: mvn compile

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    - name: Test with Maven
      run: mvn test

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -P publish -B package --file pom.xml -Dmaven.test.skip=true

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -P publish -B package --file pom.xml -Dmaven.test.skip=true
    - name: Build and Push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: viggys/my-pc
        tags: latest
        push: true
    
